name: CI/CD Docker avec Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin

      # 3️⃣ Build et tests Maven avec Jacoco
      - name: Build and Test with Maven
        run: ./mvnw clean verify

      # 4️⃣ Upload le rapport Jacoco en artifact
      - name: Upload Jacoco report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco

      # 5️⃣ Login Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t nwlcnf/mathtonsavoir-backend:latest .

      # 7️⃣ Push Docker image
      - name: Push Docker image
        run: docker push nwlcnf/mathtonsavoir-backend:latest
